theme: jekyll-theme-minimal
title: Low-Noise Diagnostics

favicon: /favicon.ico

defaults:
  - scope:
      path: ""
    values:
      image: /favicon.png

markdown: GFM
plugins:
  - jekyll-seo-tag

sass:
  style: compressed
